<?php
/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   Copyright (C) 2005 - 2017 Prasit Gebsaap. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

use Joomla\CMS\Dispatcher\Dispatcher;

/**
 * Dispatcher class for com_jongman
 *
 * @since  __DEPLOY_VERSION__
 */
class JongmanDispatcher extends Dispatcher
{
    /**
     * The extension namespace
     *
     * @var    string
     *
     * @since  __DEPLOY_VERSION__
     */
    protected $namespace = 'Soap\\Component\\Jongman';

    public function dispatch()
    {
        parent::dispatch(); // TODO: Change the autogenerated stub
    }
}